chili-publish/grafx-documentation

docs/release-notes/index.md
This PR creates the releasenotes for the Studio update to version 0.136.1
=> [Releasenotes] Studio 0.136.1

docs/release-notes/index.md
User management update: de-activate, re-activate & delete a user
=> [Releasenotes] User management update

docs/GraFx-Developers/index.md
=> Correct spelling mistake on GraFx-Developers

docs/CHILI-GraFx/guides/setup-fsso/index.md
Added sections after reading Auth0's documentation on configuring Federated SSO for Auth0 tenant administration.
=> Added "Test SSO" and "Migrate users" sections

docs/CHILI-GraFx/users/creation/index.md
Added a short section to deal with invitation emails not being received and invitation links expiring.
=> CGX Invitation expiration

.github/workflows/azure-static-web-apps-wonderful-sky-012b9bc03.yml, .github/workflows/deploy-fork.yml
This PR is trying to allow remote deploys of PRs
=> [Feature] Actions to allow remote deploy of PR

.github/workflows/accept-fork.yml, .github/workflows/deploy-fork.yml
this fix will try to fix the deployment for forked repositories
=> [Fix] Deploy for forked repos

docs/release-notes/index.md
=> [releasenotes] CHILI GraFx platform api 1.18.0

docs/release-notes/index.md
Internal [release notes](https://chilipublishintranet.atlassian.net/wiki/spaces/CPDOC/pages/4800315748/Internal+Release+Notes+-+CHILI+GraFx+Platform+-+GraFx+Platform+API+1.19.0)
=> add: release notes for Platform API 1.19.0

docs/release-notes/index.md
Release notes for Platform API hotfix release
https://chilipublishintranet.atlassian.net/wiki/spaces/CPDOC/pages/4818731009/Release+Approval+GraFx+Platform+API+1.19.1
=> add: hotfix release

Dockerfile, README.md, docker-compose.yaml
These changes are designed to streamline the onboarding experience for new developers and designers, ensuring they can get up and running with CHILI GraFx as efficiently as possible.
1. **Updated README:** The README has been comprehensively revised to better cater to newcomers. It now provides a clearer, step-by-step guide on how to contribute to the project. This structured approach will reduce initial confusion and make the project more approachable for contributors of all skill levels.
2. **Docker Integration:** To simplify the project setup, I have added Docker and docker-compose files. These files enable a seamless setup process, eliminating the common "works on my machine" problem. This change is particularly beneficial for the following reasons:
- **Consistency Across …
=> Enhancing Onboarding and Project Setup with Docker Integration and README Update

docs/release-notes/index.md
Release notes for [Platform API 1.20.0](https://chilipublishintranet.atlassian.net/wiki/spaces/CPDOC/pages/4832428078/Release+Approval+GraFx+Platform+API+1.20.0)
=> add: Platform API 1.20.0 release notes

docs/release-notes/index.md
Add a notice to the release notes that bookmarks might be broken
=> [Fix] Add broken bookmarks notice to the release-notes

docs/release-notes/index.md
Internal Release [notes](https://chilipublishintranet.atlassian.net/wiki/spaces/CPDOC/pages/4912611329/Release+Approval+GraFx+Environment+API+1.3.6)
=> add: Environment API 1.3.6 notes

docs/release-notes/index.md
=> [CHILI GraFx] Releasenotes 2024 04 04

mkdocs.yml
=> Update mkdocs.yml to fix RSS plugin issue

docs/release-notes/releaseposts/2024101501.md
Update release notes for 2024-10-15
=> [GraFx-Publisher] Releasenotes 2024-10-15

docs/release-notes/releaseposts/2024102901.md
Update release notes for 2024-10-29
=> [GraFx-Publisher] Releasenotes 2024-10-29

docs/release-notes/releaseposts/2024111901.md
Update release notes for 2024-11-19
=> [GraFx-Publisher] Releasenotes 2024-11-19

docs/release-notes/releaseposts/2024121701.md
Update release notes for 2024-12-17
=> [GraFx-Publisher] Releasenotes 2024-12-17

docs/release-notes/releaseposts/2024123101.md
Update release notes for 2024-12-31
=> [GraFx-Publisher] Releasenotes 2024-12-31

docs/release-notes/releaseposts/2025012801.md
Update release notes for 2025-01-28
=> [GraFx-Publisher] Releasenotes 2025-01-28

docs/release-notes/releaseposts/2025021101.md
Update release notes for 2025-02-11
=> [GraFx-Publisher] Releasenotes 2025-02-11

docs/GraFx-Studio/guides/image-frame/index.md
=> [GraFx Studio] imge > image

docs/GraFx-Studio/connectors/connector-keepeek-media/index.md, docs/release-notes/releaseposts/2025042502.md
Corrections for Keepeek Connector Release Notes and Docs.
=> Keepeek Typo Corrections

docs/GraFx-Developers/connectors/connectors-introduction/index.md
* Replace nested list by solution that does render correctly
* Fix typo
=> Connectors intro: Fix nested list not being rendered correctly
